# ── Required ──────────────────────────────────────────────────────────────────
reads: "./reads.fastq" #your raw sequencing reads
quality: "20" #Q score you want to filter by -- typically Q20 (1% error)
filter: "1000" #read length to filter by
medaka_model: "r1041_e82_400bps_sup_v5.0.0" #reflects nanopre chemistry for assembly polishing
path_to_comebin: "/lustre/fs4/home/jmcdonald/miniconda3/envs/comebin/bin/COMEBin/run_comebin.sh" #binner path
kraken_db: "/lustre/fs4/flam_lab/scratch/jmcdonald/kraken_db" #taxonomy database path
checkm2_db: "/ru-auth/local/home/jmcdonald/scratch/checkm2_db/CheckM2_database/uniref100.KO.1.dmnd" #checkM2 quality databse path
home: "./" #your home path
reference_genomes: "./ref_genomes" #reference genomes for coverM if using
# ── Optional ──────────────────────────────────────────────────────────────────
threads: 8
